name: weather_app
description: A Flutter weather project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^5.3.2
  retrofit: ^4.0.1
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.7
  lottie: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
